version: 2
jobs:
  build:
    docker:
        - image: circleci/node:12
    branches:
      only:
        -master
    steps:
      - add_ssh_keys:
          - fingerprints:
              - "52:fb:06:7c:29:45:56:dd:63:83:63:42:0e:85:a6:b2"
      - checkout
      - run:
          name: Install
          command: yarn install
      - run:
          name: Build
          command: yarn build